name: Networks healthcheck

on: [workflow_dispatch]
  # schedule:
  #   - cron: '0 10/5 * * *'

env:
  ACALA_PROD_AUTH_TOKEN: 'token'
  ACALA_TEST_AUTH_TOKEN: 'token'
  MOONBEAM_PROD_AUTH_TOKEN: 'token'
  MOONBEAM_TEST_AUTH_TOKEN: 'token'
  MOONPAY_PRODUCTION_SECRET: 'token'
  MOONPAY_TEST_SECRET: 'token'

  CI_KEYSTORE_PASS: 'token'
  CI_KEYSTORE_KEY_ALIAS: 'token'
  CI_KEYSTORE_KEY_PASS: 'token'

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@master
        with:
          repository: nova-wallet/nova-wallet-android
          ref: 'balances_integration_test'
          token: ${{ secrets.PAT }}

      - name: set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
          cache: gradle

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21d

      - name: Rename NDK 21 folder to NDK 23
        run: |
          rm -rf /Users/runner/Library/Android/sdk/ndk/23.1.7779620
          mv /Users/runner/Library/Android/sdk/ndk/21.4.7075529 /Users/runner/Library/Android/sdk/ndk/23.1.7779620

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add permissions
        run: chmod +x .github/workflows/networks_test.sh

      - name: Run tests
        continue-on-error: true
        uses: reactivecircus/android-emulator-runner@v2
        with:
          disable-animations: true
          profile: Nexus 5X
          api-level: 29
          script: .github/workflows/networks_test.sh

      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: /Users/runner/work/test-runner/test-runner/app/build/reports

      - name: Report
        if: steps.test.outcome=='failure'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          document: /Users/runner/work/test-runner/test-runner/app/build/reports

  report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: report

      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: androidTests/connected
